version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      - checkout

      # Install Docker CLI
      - setup_remote_docker:
          docker_layer_caching: true

      # Log in to Docker Hub
      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build Docker image
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/two-tier-application:latest .

      # Push Docker image
      - run:
          name: Push Docker image
          command: docker push $DOCKERHUB_USERNAME/two-tier-application:latest

workflows:
  build_and_deploy:
    jobs:
      - build-and-push
